spring:
  name: ecommerce-local
  datasource:
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/myntra_clonee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: 
      minimumIdle: 5
      maximumPoolSize: 10
      idleTimeout: 30000
      poolName: ecommerce-pool-local	
      maxLifetime: 2000000
      connectionTimeout: 30000  # fixed typo here
  jpa:
    hibernate:
      ddl-auto: update  
    generate-ddl: false
    show-sql: true 
    properties:
      hibernate:
        show_sql: DEBUG
        format_sql: true 
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

  jackson: 
    serialization:
      write-dates-as-timestamps: false

server:
  port: 1024
  servlet:
    context-path: /ecommerce-api-local

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.majorproject.ecommerce_web: DEBUG

file:
  upload-dir: upload/

app:
  max-file-size: 209715200  # 200MB in bytes (used in @Value)
